### ISSUE TITLE
Multiple RTU master 

### ISSUE THREAD

**Issue by ethicstechOSS** [ljean/modbus-tk#100]
Hi. I have three slaves and my gateway is acting as master device. To avoid the time delay b/w one master and multiple slaves, I would like to run 3 masters on my gateway and each master will communicate with only one slave to read the slave data as soon as possible. Can I run three master programs simultaneously on my gateway?. 

TIA.

**Comment by ljean** [comment]
Hello,
You should be able to do that :)
Best
luc
