### ISSUE TITLE
Reading Signed Values

### ISSUE THREAD

**Issue by deepak5g** [ljean/modbus-tk#101]
Hello,

I am trying to read the signed values, 

This is my step for reading the data, help me in reading the signed values
```
master =  modbus_tcp.TcpMaster("CC.XXX.20.242", 4161, 10.0)
master.execute(1, cst.READ_HOLDING_REGISTERS, 36352, 68)
```

Thanks in advance,
Deepak

**Comment by ljean** [comment]
You can try to set a custom data format. Something like this should work

```
quantity = 68
data_format = ">" + (quantity * "h")
master.execute(1, cst.READ_HOLDING_REGISTERS, 36352, quantity, data_format= data_format)
```
