### ISSUE TITLE
FYI: MicroPython port now available

### ISSUE THREAD

**Issue by seanlano** [ljean/modbus-tk#107]
This isn't an issue per sé, but I just wanted to drop a link to a MicroPython port I have made, forked from `modbus-tk`. So far it only supports RTU Master mode (i.e. no TCP and no slave mode), as this was all I needed in my MicroPython application - the other modes probably wouldn't be too hard to port. 

It is available at https://gitlab.com/extel-open-source/micropython-modbus , of course under the same LGPL license. Unfortunately because I used GitLab for the hosting my fork doesn't show up under the GitHub "Forks" page - I wanted to let the previous developers know though and figured an issue would be the easiest way. 

Thanks!

**Comment by ljean** [comment]
Thanks for the info. I've put a link to your project in the README.
