### ISSUE TITLE
LICENSE file is missing in the tarball available from PyPi

### ISSUE THREAD

**Issue by texierp** [ljean/modbus-tk#114]
hello @ljean 

I plan to package modbus-tk in Buildroot.
So, would it be possible to put the license file in the archive
available on PyPi ?

It's just to satisfy the legal informations in fact :)

Thanks !
/Pierre-Jean

**Comment by ljean** [comment]
Hello Pierre-Jean,

I've released version 1.0.0 of modbus-tk with a fix for this legal issue :)

**Comment by texierp** [comment]
Oh nice :)

Many thanks

Pierre-Jean
