### ISSUE TITLE
 Raspberry Pi 4B server error: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by wenminghit** [ljean/modbus-tk#138]
when i run modbusTCPslave on  Raspberry Pi 4B，it prompt  :server error: [Errno 13] Permission denied
run this 
    slave_1 = server.add_slave(ID)

python  :server error: [Errno 13] Permission denied

**Comment by ljean** [comment]
Your system may require specific permissions for running a TCP server. Make sure the user runing your python scripts has the right permissions.
I hope it helps
