### ISSUE TITLE
modbus simulator using modbus-tk and kivy

### ISSUE THREAD

**Issue by dhoomakethu** [ljean/modbus-tk#50]
Hi,

JFYI.
I have been working on modbus simulator based on modbus-tk and gui built with kivy .
https://github.com/dhoomakethu/kivy-modbus-simu

feel free to use/share and report any issues.
At present , It only supports modbus tcp ,but I am working to enable serial part as well.

Regards
Sanjay

**Comment by ljean** [comment]
Hello,

I've merged your pull request
