### ISSUE TITLE
Include Slave ID in hook/callbacks

### ISSUE THREAD

**Issue by jg111** [ljean/modbus-tk#52]
Normally with one Slave/ModbusBlock and a "modbus.ModbusBlock.setitem" hook, the callback works perfectly fine. But, If the server is comprised of multiple Slave/ModbusBock instances (and all have the same register numbers), when the callback occurs, you are given the ModbusBlock, register, register value, etc but not the Slave ID. This makes is difficult to figure out which Slave the client was talking unless you building in your own map/lookup.

Ideally, it would be nice if the callback included the Slave ID as part of its arguments.

**Comment by ljean** [comment]
Actually, I've just added the name to the ModbusBlock object. It gives the ability to make difference between blocks when handing the hook
