### ISSUE TITLE
Rewrite the modbus-tk project's repository description.

### ISSUE THREAD

**Issue by davivcgarcia** [ljean/modbus-tk#54]
Hi,

I was looking for information about the project and when I saw the repository's description (**Automatically exported from code.google.com/p/modbus-tk**) I thought this project was not being maintained anymore. Checking the commits, I figured out that this project is still active! :smile: 

Not sure if you all agree, but the description should change to the original repository description at Google Code (**Create Modbus app easily with Python**) which is very clear and objective.

Thanks,
Davi Garcia

**Comment by ljean** [comment]
Hello Davi,

Thanks for this issue. I didn't notice the description was automatically changed. This is fixed now.

Best
luc
