### ISSUE TITLE
Modbus_tk Python code

### ISSUE THREAD

**Issue by sameer546** [ljean/modbus-tk#62]
Hi I'm using Micrologix 1400 PLC as Master and sending data to my pc(Slave).
I have used the third party software(trial version), I'm able to receive the data in the register address 40001, slave id=1.

I'm using the following code:
import sys

#add logging capability
import logging
import threading

import modbus_tk
import modbus_tk.defines as cst
import modbus_tk.modbus as modbus
import modbus_tk.modbus_rtu as modbus_rtu
import serial

logger = modbus_tk.utils.create_logger(name="console", record_format="%(message)s")
    
if __name__ == "__main__":
    #Create the server
    server = modbus_rtu.RtuServer(serial.Serial('COM4'))
        
    try:
        logger.info("running...")
        logger.info("enter 'quit' for closing the server")
        
        server.start()

        slave_1 = server.add_slave(1)
        slave_1.add_block('0', cst.READ_INPUT_REGISTERS, 40001, 22)
        while True:
            cmd = sys.stdin.readline()
            args = cmd.split(' ')
            if cmd.find('quit')==0:
                sys.stdout.write('bye-bye\r\n')
                break
            elif args[0]=='add_slave':
                slave_id = int(args[1])
                server.add_slave(slave_id)
                sys.stdout.write('done: slave %d added\r\n' % (slave_id))
            elif args[0]=='add_block':
                slave_id = int(args[1])
                name = args[2]
                block_type = int(args[3])
                starting_address = int(args[4])
                length = int(args[5])
                slave = server.get_slave(slave_id)
                slave.add_block(name, block_type, starting_address, length)
                sys.stdout.write('done: block %s added\r\n' % (name))
            elif args[0]=='set_values':
                slave_id = int(args[1])
                name = args[2]
                address = int(args[3])
                values = []
                for v in args[4:]:
                    values.append(int(v))
                slave = server.get_slave(slave_id)
                slave.set_values(name, address, values)
                values = slave.get_values(name, address, len(values))
                sys.stdout.write('done: values written: %s\r\n' % (str(values)))
            elif args[0]=='get_values':
                slave_id = int(args[1])
                name = args[2]
                address = int(args[3])
                length = int(args[4])
                slave = server.get_slave(slave_id)
                values = slave.get_values(name, address, length)
                sys.stdout.write('done: values read: %s\r\n' % (str(values)))
            else:
                sys.stdout.write("unknown command %s\r\n" % (args[0]))
    finally:
        server.stop() 

I'm getting the following error;
Modbus Error: Exception code = 2

Kindly help me out in reading the registers with right syntax.

**Comment by ljean** [comment]
It seems to be a addressing error. Try to use address 1 rather than 40001.
