### ISSUE TITLE
Error de comunicación

### ISSUE THREAD

**Issue by sistemasmc1986** [ljean/modbus-tk#65]
Estuve intentando comunicar con un arduino MEGA pero simpre me tiraba un error: 
modbus_tk.exceptions.ModbusInvalidResponseError: Response length is invalid 0
al depurar el error, comunicaba totalmente sin ninguna falla,
solucione el bug, añadiendo tiemos en la rutina:

def threadsafe_function(fcn):
    """decorator making sure that the decorated function is thread safe"""
    lock = threading.RLock()
    time.sleep(0.02) ## tiempo añadido

```
def new(*args, **kwargs):
    """lock and call the decorated function"""
    lock.acquire()
    time.sleep(0.02)## tiempo añadido
    try:
        ret = fcn(*args, **kwargs)
        time.sleep(0.02)## tiempo añadido
    except Exception as excpt:
        raise excpt
    finally:
        lock.release()
    return ret
return new
```

**Comment by ljean** [comment]
Can you please explain the problems in english?

2016-10-05 6:07 GMT+02:00 sistemasmc1986 <notifications@github.com>:

**Comment by sistemasmc1986** [comment]
I try to communicate Arduino with python using his Librarie, but allways stay in error, the interpreter says: modbus_tk.exceptions.ModbusInvalidResponseError: Response length is invalid 0,

Solve it by adding time to the function you mentioned.
