### ISSUE TITLE
How to get the log？

### ISSUE THREAD

**Issue by zhiyinyouzhao** [ljean/modbus-tk#66]
Hi，
I use modbus_tk finish a slave.py. 
Then use client software connect to the slave，it‘s test ok.
And now,I wan to get every client's IP,port and protocol.
How can I do? thanks.
slave.py

#!/usr/bin/python2.7
# -*- coding: utf-8 -*-
# filename: server_example.py

import modbus_tk
import modbus_tk.modbus_tcp as modbus_tcp
import modbus_tk.defines as mdef
import threading
import sys

logger = modbus_tk.utils.create_logger(name='console', record_format='%(message)s')

if __name__ == '__main__':
    try:
        logger.info("running...")
        logger.info("enter 'quit' for closing the server")

        server = modbus_tcp.TcpServer(port=502)
        server.start()
        #creates a slave with id 0
        slave1 = server.add_slave(1)
        #add 2 blocks of holding registers
        slave1.add_block('a', mdef.HOLDING_REGISTERS, 0, 100)  #address 0, length 100
        slave1.add_block('b', mdef.HOLDING_REGISTERS, 200, 20) #address 200, length 20

        #create another slave with id 5
        slave5 = server.add_slave(5)
        slave5.add_block('c', mdef.COILS, 0, 100)
        slave5.add_block('d', mdef.HOLDING_REGISTERS, 0, 100)

        #set the values of registers at address 0
        slave1.set_values('a', 0, range(100))

        while True:
            cmd = sys.stdin.readline()
            if cmd.find('quit')==0:
                sys.stdout.write('bye-bye\r\n')
                sys.exit(0)

    finally:
        server.stop()

**Comment by ljean** [comment]
This is not really an issue and thi skins of question should be asked on StackOverflow for example.

However, I think you can get info about client with the `getpeername` method of a socket.

You can can access the socket thanks to the `_sock` argument of both `TcpMaster`and `TcpSlave`

I didn't test by myself but I hope it works.
