### ISSUE TITLE
When I run mysimu.py in windows 7 sp1 in tcp/ip mode, I got an Exception

### ISSUE THREAD

**Issue by moebiusever** [ljean/modbus-tk#68]
Details: 
File "C:\Python34\lib\site-packages\modbus_tk\simulator.py", line 142, in __init__
    raise Exception("%s platform is not supported yet" % os.name)
Exception: nt platform is not supported yet
I think it is a bug of simulator.py,  in line 137
if os.name == "posix": 
should be 
elif os.name == "posix":
While I do like that, it works.

**Comment by ljean** [comment]
Yes! It's right
