### ISSUE TITLE
device act as a  modbus server, how can I set the float data

### ISSUE THREAD

**Issue by adcyh1327** [ljean/modbus-tk#77]
hello,
    when I set the register of integer, the result is no problem, but when the register is float, the final result is changed to integer forcibly. How to set the float register correctly

values = []
     values.append(3.14)
     slave = server.get_slave(slaveCfg['slaveID'])
     slave.set_values(slaveCfg['slaveName'], 0, values)

the result of modbus client read is 3(integer), not 3.14(float)

**Comment by ljean** [comment]
hello,

You should manage the conversion between load and registers manually. Something like this should work

```
   import struct


    def set_pi(self, args):
        """change the value of some registers"""
        address = int(args[1])

        # operates on slave 1 and block foo
        slave = self.server.get_slave(1)

        pi_bytes = [int(a_byte) for a_byte in struct.pack("f", 3.14)]

        pi_register1 = pi_bytes[0] * 256 + pi_bytes[1]
        pi_register2 = pi_bytes[2] * 256 + pi_bytes[3]

        slave.set_values("foo", address, [pi_register1, pi_register2])
```
