### ISSUE TITLE
Modbus Exception Code 2

### ISSUE THREAD

**Issue by KyungChun** [ljean/modbus-tk#91]
Hi,

When modbus_tcp server (slave) is running as holding register function(code 3) and modbus_tcp client (master) is configured to read_coils (code 1), currently "Modbus Error: Exception code =2 (illegal data address)" is generated. But, i think that the exception code will be code =1 (illegal function).

Please, explain the reason for the exception.

**Comment by ljean** [comment]
I didn't try myself but I think you are right. I will try to fix that when possible
