### ISSUE TITLE
README.md hence github references wrong version

### ISSUE THREAD

**Issue by GadgetSteve** [ljean/modbus-tk#99]
README.md States: Current version is 0.5.7 this is incorrect the latest version at the time of this ticket is 0.5.8 and should this ticket be addressed it will be at least 0.5.9

I suggest creating a release script which updates the "current" version everywhere needed, (i.e. README.md, metadata, embedded version, etc. and then creates the github release and does the publishes to pypi all in a single step.

**Comment by ljean** [comment]
Hello Gadget Steve,

That's a good suggestion. Do you already have some info for such a release script?

Best
luc
